apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: db
  labels:
    id: "905672"
    app: wordpress-stack
    env: dev
type: Opaque
data:
  SECURITY_TOKEN: d29yZHByZXNzCg==         ## base64 encoded value of original password. Use command: echo -n wordpress | base64
  PASSWORD: d3AxMjM0NQ==