apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wp
  labels:
    id: "905672"
    app: wordpress-stack
    env: dev
data:
  WORDPRESS_DB_HOST: "mariadb-service.db.svc.cluster.local:3306"
