apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wp
  labels:
    id: "905672"
    app: wordpress-stack
    env: dev
spec:
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 80
  selector:
    id: "905672"