apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proxy
  labels:
    id: "905672"
    app: wordpress-stack
    env: dev
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://wordpress-service.wp.svc.cluster.local:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
