apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: "905672"
    app: wordpress-stack
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "905672"
  template:
    metadata:
      labels:
        id: "905672"
        app: wordpress-stack
        env: dev
    spec:
      containers:
      - name: nginx-proxy
        image: chiragbaghra/nginx-proxy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-map  
